### ISSUE TITLE
Integrate SingleFile with the Safari Share Extension framework

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFile#1381]
The goal would be to include a “Save page to Notes” and “Save selection to Notes” in the list of suggestions.

**Comment by appledispatch** [comment]
I just [posted an article](https://appledispatch.substack.com/p/apple-notes-unleashed-series-web) for my publication, Apple Dispatch, about integrating SingleFile, Apple Notes and Safari that is relevant to this suggested feature request and also how to harness the power of SingleFile in general.

The way that I'm sharing items now is by Right-clicking the downloaded HTML file, selecting Share…, and then choosing Notes. It would be great to have the tighter integration built directly into the Safari Share Sheet. 

Thanks for your continued efforts on such an amazing tool!

**Comment by gildas-lormeau** [comment]
Thank you very much for the article. I did a quick test in Safari and it looks promising. The good news is that it supports the [`navigator.share()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) API.

FYI, here is the test I did:
1. Open https://www.example.com in Safari
2. Open the JavaScript console (via the menu `Develop > Show JavaScript Console`)
3. Paste the code below in the console and press Enter
```js
document.onclick = () => navigator.share({ files: [new File([ document.documentElement.outerHTML ], "example.html")]})
```
4. Click anywhere on the page
5. A popup should allow you to add the page in Notes

I will do a more advanced integration test in SingleFile, I'll keep you informed ;)

**Comment by appledispatch** [comment]
That is absolutely fantastic! I just ran the code you posted and it works perfectly! Thanks for sharing it. 

I noticed if I click away from the share sheet, without sharing to Notes, I get these errors in the console: (Unhandled Promise Rejection: InvalidStateError: share() is already in progress) and this one: (Unhandled Promise Rejection: AbortError: Abort due to cancellation of share.) Maybe this is the intended behavior?

I [put the word out about my article](https://www.reddit.com/r/macapps/comments/1aqv7v8/apple_notes_web_clipper_replacement_for_evernote/) highlighting SingleFile over at the excellent [/MacApps](https://www.reddit.com/r/macapps/) subreddit and they are really digging it there. It’s turning on a lot of people (≈ 3.9k currently) to your wonderful extension in the Apple community. 

Yes indeed, please keep me in the loop as things progress. I will be posting about this @[Apple Dispatch](https://appledispatch.substack.com/) for my Apple Notes series once this feature becomes a reality.

Truly exciting developments!

**Comment by gildas-lormeau** [comment]
It's implemented. I added a new option `share page` in the `Destination` section. When checked, a banner with a "Share page..." button will appear at the top of the page when you save it. By clicking on this button, you will be able to share the page on Notes., see the screenshot below Unfortunately, this button requires an extra click, but I have no choice from a technical point of view.

![image](https://github.com/gildas-lormeau/SingleFile/assets/396787/d213f2c4-8cdf-466e-b824-585fcfcc990e)

**Comment by appledispatch** [comment]
Thanks so much for your excellent work on this new feature! I love to see SingleFile getting even tighter integration with Safari and Notes. 

Can't wait to see this drop on the App Store.

**Comment by gildas-lormeau** [comment]
The new version (1.2.0) is available for download on the App store.

**Comment by appledispatch** [comment]
This is absolutely killer! Is there a way for this new implementation to also work for Save selection to Notes?

**Comment by appledispatch** [comment]
That's great! Is there a way for the 'Share page…' button to change to 'Share selection…' when choosing that option from the context menu?

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion, it is fixed. The fix will be available in the next version.

**Comment by appledispatch** [comment]
Any time. Well done!

**Comment by appledispatch** [comment]
Is there a way to get macOS Spotlight to index the HTML files saved by SingleFile? It seems that files saved to Apple Notes can only be searched by title and not by the text contained within each HTML document.

**Comment by gildas-lormeau** [comment]
I don't think it's possible. It looks like it's a "bug" in Notes, see https://discussions.apple.com/thread/251960240?answerId=253757819022.

However, you can search for attached pages with the Finder in `~/Library/Group\ Containers/group.com.apple.notes/Accounts`.

**Comment by appledispatch** [comment]
You're definitely on to something with that Apple Discussion thread. I was able to find out that Spotlight will index and search text content within Safari webarchives, but Notes cannot do the same. It looks like Apple did not implement that part of the Spotlight Index API in Notes. 

So, it seems pretty clear why Notes cannot search SingleFile archives, but I'm still not sure why Spotlight can't search them. Maybe, Apple only allows the API to work on its own HTML archive format?
