### ISSUE TITLE
Additional Page Text Added to SingleFile Download

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#250]
**Describe the bug**

Observed this bug on certain pages of washingtonpost.com.  It is not triggered on all washingtopost singlefile saved pages for some reason.  It also may have appeared on other sites, but i didnt notice the site when it occurred previously, just that it was happening.  

During the process of saving the page, text within the page is duplicated and then saved with the duplicated lines.  This process actually changes the viewed html of the original page until a page refresh is done.

**To Reproduce**
go to https://www.washingtonpost.com/politics/a-majority-of-house-democrats-backs-impeachment-according-to-an-analysis-by-the-washington-post/2019/08/02/5f28dbbc-b314-11e9-8f6c-7828e68cb15f_story.html?utm_term=.ccce28a744a7

Scroll page completely to ensure all pictures/elements load.  Then click singlefile.

Observe duplicated text in page.  Review saved file to see duplicated text.

**Expected behavior**
Singlefile saves page in html format exactly as originally observed.  Original page is unmodified from original viewing.

**Screenshots**
https://drive.google.com/file/d/1KPNURyVL6eyPTe6mvR1fRGgdliuH4gwX/view?usp=drive_web

**Environment**
 - Operating System: Microsoft Windows 10 Education (x64) Build 17134.829 (1803/RS4)

 - Browser: Firefox 68.1, Opera Version:60.0.3255.170
 - Version: [64bit]
 - 32GB RAM

**Additional context**
same thing happened using Opera on other pages.  Set up brand new Firefox browser just to test.  Only extension added was singlefile and no user scripts added.

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. Before I modify my settings in order to bypass the paywall, could you please tell me if disabling the option "Images > Save deferred images" fixes the issue?

**Comment by sj365** [comment]
I will check right now

**Comment by sj365** [comment]
I checked using singlefile in FFx and Opera; the problem does not occur with Images > Save deferred images unchecked.  Is it better to just make this option setting the default for singlefile?  Is there any downside to doing this?

**Comment by gildas-lormeau** [comment]
I'm wondering too. Most of the time, this option works well and allows to save deferred images w/o scrolling into the page.

Could you please do the following test and tell me if it fixes the issue?
 - Enable "Images > Save deferred images"
 - Export the settings
 - Edit the exported file and replace `loadDeferredImagesBlockCookies: true,` with `loadDeferredImagesBlockCookies: false,`
 - Import the modified settings in SingleFile
 - Save the page

**Comment by gildas-lormeau** [comment]
I was able to reproduce your issue. The procedure I described in the previous pst did notwork for me. I'm trying to see if there's a bug in the code.

**Comment by sj365** [comment]
I dont know if this is related but singlefile also has consistent trouble saving long pages, particularly newspaper pages.  This example uses washingtonpost and although it saved the news part ok, the entire comments section was blanked out.  I had scrolled down maybe 50 or so comments before saving.  Going forward I will keep track of when/where these errors occur to see if there is correlation between site/browser.  https://www.washingtonpost.com/nation/2019/08/03/active-shooter-cielo-vista-mall-area-el-paso-police-say/?utm_term=.0e135b59003f

**Comment by gildas-lormeau** [comment]
Again, thank you for having reported this issue. By debugging it, I found a nasty typo that, I think, was responsible of the issue. I cannot reproduce it anymore in the version 1.11.20 I just published. 

Regarding the second issue, I cannot do any test on https://www.washingtonpost.com/nation/2019/08/03/active-shooter-cielo-vista-mall-area-el-paso-police-say/?utm_term=.0e135b59003f. I need to pay to view the article. Could you tell me if it's better with the latest version or find another example?

**Comment by sj365** [comment]
no comments - works now with latest firefox, but not in chrome or opera
----------------------------------
https://www.washingtonpost.com/nation/2019/08/03/officer-was-doing-welfare-check-her-he-fatally-shot-her-after-firing-dog/?utm_term=.be969d58bb3b

https://www.washingtonpost.com/nation/2019/08/03/active-shooter-cielo-vista-mall-area-el-paso-police-say/?utm_term=.8763af11757f



missing graphics - doesnt capture page correctly in any program, singlefile, savepage web, webscrapbook
================================
https://www.washingtonpost.com/graphics/2019/investigations/dea-pain-pill-database/?utm_term=.ea178e2bf824


i know you are getting a subscription soon, but in the meantime for testing purposes on Firefox the best thing is to use the available tools.  All thats needed for Firefox tests are:
Tampermonkey
Ublock origin - default filters plus MVPS HOSTS under Multipurpose
Burlesco userscript
anti-paywall xpi

**Comment by gildas-lormeau** [comment]
Do you confirm the issue you initially reported is fixed though? i.e. "Additional Page Text Added to SingleFile Download"

The second issue related to comments is not the same one, I think.

**Comment by sj365** [comment]
no comments - works now with latest firefox, but not in chrome or opera
----------------------------------
https://www.washingtonpost.com/nation/2019/08/03/officer-was-doing-welfare-check-her-he-fatally-shot-her-after-firing-dog/?utm_term=.be969d58bb3b

https://www.washingtonpost.com/nation/2019/08/03/active-shooter-cielo-vista-mall-area-el-paso-police-say/?utm_term=.8763af11757f



missing graphics - doesnt capture page correctly in any program, singlefile, savepage web, webscrapbook
================================
https://www.washingtonpost.com/graphics/2019/investigations/dea-pain-pill-database/?utm_term=.ea178e2bf824


i know you are getting a subscription soon, but in the meantime for testing purposes on Firefox the best thing is to use the available tools.  All thats needed for Firefox tests are:
Tampermonkey
Ublock origin - default filters plus MVPS HOSTS under Multipurpose
Burlesco userscript
anti-paywall xpi

**Comment by sj365** [comment]
The original issue of the duplicated text seems to be fixed.  As i go through the day I will watch for any errors.  The issue with blanked comments on the news site does seem to work now on Firefox only.  The same issue is still occurring using Opera and Chrome.  

I should have started a different thread for the missing graphics issue from the news site.  This is still affecting all three browsers and the top three applications as of now.

**Comment by gildas-lormeau** [comment]
I was not able to reproduce your issue with comments in Chrome. Here is a zip file containing the 2 saved pages with SingleFile in Chrome.

[Saved pages.zip](https://github.com/gildas-lormeau/SingleFile/files/3465247/Saved.pages.zip)


Regarding the graphics, it seems the problem is that washingtonpost.com does not allows extensions to do a screenshot of the <canvas> element used to display it. Today, I don't know how to circumvent this.

**Comment by gildas-lormeau** [comment]
I've filled a new issue (https://github.com/gildas-lormeau/SingleFile/issues/251) for the problem related to the embedded graphic which is not saved.

**Comment by sj365** [comment]
Thanks for filing the new issue.  As far as the comments issue, I havent changed any default settings to affect the saved pages.  If I can get more info about it i will let you know.  Thanks.

**Comment by gildas-lormeau** [comment]
You're welcome :)
