### ISSUE TITLE
Using CLI received UnhandledPromiseRejectionWarning: Error: net::ERR_SSL_PROTOCOL_ERROR on certain pages

### ISSUE THREAD

**Issue by hyperalghorithm** [gildas-lormeau/SingleFile#253]
using gitbash on windows 10 or terminal on ubuntu 18.04
win10:  ./single-file https://www.baymen.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
ub18.04:   ./single-file https://www.baymen.com/  test.html --browser-executable-path='usr/bin/chrome-stable'
few websites that failed so far:
https://www.americanas.com.br/
https://www.beymen.com/
https://www.binary.com/

they work fine with the browser extension installed.
both times used chrome v 76 (latest upto date)

error output:

```
$ ./single-file https://www.baymen.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
ERROR: The process with PID 2460 (child process of PID 12120) could not be terminated.
Reason: There is no running instance of the task.
(node:4608) UnhandledPromiseRejectionWarning: Error: net::ERR_SSL_PROTOCOL_ERROR at https://www.baymen.com/
    at navigate (C:\Users\User\Downloads\SingleFile-master\SingleFile-master\cli\node_modules\puppeteer-core\lib\FrameManager.js:121:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\User\Downloads\SingleFile-master\SingleFile-master\cli\node_modules\puppeteer-core\lib\helper.js:111:15)
    at Page.goto (C:\Users\User\Downloads\SingleFile-master\SingleFile-master\cli\node_modules\puppeteer-core\lib\Page.js:674:49)
    at Page.<anonymous> (C:\Users\User\Downloads\SingleFile-master\SingleFile-master\cli\node_modules\puppeteer-core\lib\helper.js:112:23)
    at Object.exports.getPageData (C:\Users\User\Downloads\SingleFile-master\SingleFile-master\cli\back-ends\puppeteer.js:100:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gildas-lormeau** [comment]
Well, there are 3 different issues in this report.
 * I cannot navigate on https://www.baymen.com/ (with a "a") and https://www.americanas.com.br/ in my browser. This is why a `ERR_SSL_PROTOCOL_ERROR` error is thrown.
 * The issue on https://www.beymen.com/ (with a "e") was related to the fact that this page overloads the URL constructor (https://developer.mozilla.org/en-US/docs/Web/API/URL). It should be fixed now.
 * The issue on https://www.binary.com/ was related to the fact that the page does a JS redirect which was preventing the script to run correctly. Now, if this issue happens then the page will be automatically re-captured with the redirected URL (e.g. https://www.binary.com/fr/home.html)

**Comment by hyperalghorithm** [comment]
Ah! my bad! I pasted the wrong url. it was beymen (with an 'e'). 

I can navigate to https://www.americanas.com.br/ and still get the same error as pointed before.

on https://www.binary.com/ i get this
` ./single-file https://www.binary.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
(node:6844) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
    at Promise (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\Connection.js:182:12)
    at ExecutionContext._evaluateInternal (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:112:23)
    at DOMWorld.evaluate (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\User\User\SingleFile\cli\node_modules\puppeteer-core\lib\Page.js:827:43)
    at Page.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:112:23)
    at Object.exports.getPageData (C:\User\User\Downloads\SingleFile\cli\back-ends\puppeteer.js:105:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
also can you check https://www.binomo.com/ it just goes on an endless loop. doesn't error out nor writes a file.

**Comment by gildas-lormeau** [comment]
Did you update the code of SingleFile?

**Comment by hyperalghorithm** [comment]
Yes i have

**Comment by gildas-lormeau** [comment]
That's weird, the error "Execution context was destroyed" should be intercepted... Could you add `console.log("NEW URL IS", url)` after the following line and tell me what it displays?

https://github.com/gildas-lormeau/SingleFile/blob/544bb12ffbb9ac4cbe0b2a8131c7caff43c1191a/cli/back-ends/puppeteer.js#L130

**Comment by gildas-lormeau** [comment]
Can you also show me the error on https://www.americanas.com.br/  please?

**Comment by hyperalghorithm** [comment]
`$ ./single-file https://www.binary.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
NEW URL IS https://www.binary.com/
(node:780) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Execution context was destroyed.
    at Promise (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\Connection.js:182:12)
    at ExecutionContext._evaluateInternal (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:112:23)
    at DOMWorld.evaluate (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\Page.js:827:43)
    at Page.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:112:23)
    at Object.exports.getPageData (C:\Users\User\Downloads\SingleFile\cli\back-ends\puppeteer.js:105:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by hyperalghorithm** [comment]
for americanas

`$ ./single-file https://www.americanas.com.br/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
ERROR: The process with PID 10800 (child process of PID 7628) could not be terminated.
Reason: There is no running instance of the task.
(node:5752) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_RESET at https://www.americanas.com.br/
    at navigate (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\FrameManager.js:121:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:111:15)
    at Page.goto (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\Page.js:674:49)
    at Page.<anonymous> (C:\Users\User\Downloads\SingleFile\cli\node_modules\puppeteer-core\lib\helper.js:112:23)
    at Object.exports.getPageData (C:\Users\User\Downloads\SingleFile\cli\back-ends\puppeteer.js:100:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by gildas-lormeau** [comment]
Thanks for the logs. For binary.com, the issue is that the URL after the redirect did not change as if the website could not geolocate you... On my end, I'm always redirected to the french version on the website.

Can you try to remove these lines please and tell me if it fixes the issue?
https://github.com/gildas-lormeau/SingleFile/blob/544bb12ffbb9ac4cbe0b2a8131c7caff43c1191a/cli/back-ends/puppeteer.js#L131

https://github.com/gildas-lormeau/SingleFile/blob/544bb12ffbb9ac4cbe0b2a8131c7caff43c1191a/cli/back-ends/puppeteer.js#L135-L137

**Comment by hyperalghorithm** [comment]
> Thanks for the logs. For binary.com, the issue is that the URL after the redirect did not change as if the website could not geolocate you... On my end, I'm always redirected to the french version on the website.
> 
> Can you try to remove these lines please and tell me if it fixes the issue on binary.com?
> https://github.com/gildas-lormeau/SingleFile/blob/544bb12ffbb9ac4cbe0b2a8131c7caff43c1191a/cli/back-ends/puppeteer.js#L131
> 
> https://github.com/gildas-lormeau/SingleFile/blob/544bb12ffbb9ac4cbe0b2a8131c7caff43c1191a/cli/back-ends/puppeteer.js#L135-L137

The output was kind of interesting. 
```
$ ./single-file https://www.binary.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/en/home.html
```
Looks like it keept redirecting me untill a finall url where it outputed the test.html.

**Comment by gildas-lormeau** [comment]
Indeed...

**Comment by gildas-lormeau** [comment]
If you do the same test multiple times, do you see the same number of `NEW URL IS https://www.binary.com/` displayed?

**Comment by hyperalghorithm** [comment]
test 1:
```$ ./single-file https://www.binary.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/en/home.html
```
test 2:
```
$ ./single-file https://www.binary.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/en/home.html
```
test 3:
```
$ ./single-file https://www.binary.com/  test.html --browser-executable-path='C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/
NEW URL IS https://www.binary.com/en/home.html
```
I think this is enough for test purpose sake, The number is not the same in any instance.

**Comment by gildas-lormeau** [comment]
@hyperalghorithm Are your npm modules (e.g. pupetter) up to date?

**Comment by gildas-lormeau** [comment]
For americanas, you're seeing the same issue that I see in my browser. The server refuses to serve the page and closes the connection. Does your script run in the cloud or in a "strange place" that could not be localized?

**Comment by gildas-lormeau** [comment]
For binomo, the issue is due to the fact that the website is constantly retrieving resources from the web. Thus, SingleFile is not able to determine when the page is fully loaded. To fix this pass the switch `--browser-wait-until=networkidle2` when running the script.

If you see another *type of* issue, please create another issue or send me an email. My goal is to close issue reports (by fixing the associated issue). Right now, I'm almost unable to say if I can close this one since there are 5 types of different issues in the current report.

**Comment by hyperalghorithm** [comment]
> If you see another _type of_ issue, please create another report or send me an email with all the type of issues in the same email. My goal is to close reports (by fixing the associated issue). Right now, I'm almost unable to say if I can close this one since there are 4 types of different issues in it. Edit: I don't want to sound harsh and I'm sorry if it seems so, it's mainly to make sure that the reports are easy for everyone to follow.

I do apologize for it, I didn't want to suddenly spam you with issues.



> For americanas, you're seeing the same issue that I see in my browser and on the command line interface. The server refuses to serve the page and closes the connection. Does your script run in the cloud or in a "strange place" that could not be geolocated?

The website itself loads fine in my browser, I don't see a reason why it shouldn't be available.



> For binomo, the issue is due to the fact that the website is constantly retrieving resources from the web. Thus, SingleFile is not able to determine when the page is fully loaded. To fix this, pass the switch `--browser-wait-until=networkidle2` when running the script.

so far binary works great! thanks! how ever americanas and binomo still aren't quite there yet. I've tried load,networkidle2 and domcontentloaded for --browser-wait-untill flag and nothing. 
americanas still shows net::ERR_CONNECTION_RESET on networkidle0

It stalls until there is ```UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded```
(Let me know if this requires a new issue

**Comment by gildas-lormeau** [comment]
> > For americanas, you're seeing the same issue that I see in my browser and on the command line interface. The server refuses to serve the page and closes the connection. Does your script run in the cloud or in a "strange place" that could not be geolocated?
> 
> The website itself loads fine in my browser, I don't see a reason why it shouldn't be available.

For example, because your browser is in not in Portuguese. However that's not the case here. I finally was able to see this website in my browser and save the page by using a proxy in the US. Could you please insert this code `browserOptions.args.push("--proxy-server=181.214.43.115:3129");` after the following line and tell me if it helps to fix this issue?
https://github.com/gildas-lormeau/SingleFile/blob/f6efdc97bb8e803299cd7b3cc04abd58a2d17de8/cli/back-ends/puppeteer.js#L60

(If you see an error related to the proxy, pick another here for example: https://www.us-proxy.org/)

For your information, here is my saved file [test-puppeteer-americanas.zip](https://github.com/gildas-lormeau/SingleFile/files/3517905/test-puppeteer-americanas.zip)

> 
> > For binomo, the issue is due to the fact that the website is constantly retrieving resources from the web. Thus, SingleFile is not able to determine when the page is fully loaded. To fix this, pass the switch `--browser-wait-until=networkidle2` when running the script.
> 
> so far binary works great! thanks! how ever americanas and binomo still aren't quite there yet. I've tried load,networkidle2 and domcontentloaded for --browser-wait-untill flag and nothing.
> americanas still shows net::ERR_CONNECTION_RESET on networkidle0
> 

For your information, the error "net::ERR_CONNECTION_RESET" means that the server decided to close the connection. It does this in its sole discretion. This issue is not related to the one on binomo and binary at all.

> It stalls until there is `UnhandledPromiseRejectionWarning: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded`
> (Let me know if this requires a new issue)

For binomo, I run `single-file https://www.binomo.com test-puppeteer-binomo.html --browser-debug=false --browser-wait-until=networkidle2 --browser-executable-path=[...]` and the saved file is okay on my end. Here it is: 
[test-puppeteer-binomo.zip](https://github.com/gildas-lormeau/SingleFile/files/3517916/test-puppeteer-binomo.zip)

If you run the same command by adding the switch `--browser-debug=true`, go to the network panel in the developer tools (press F12), do you see a bunch of requests that are always in flight or anything particular?

**Comment by gildas-lormeau** [comment]
Here's a recap of the statuses for each issue (checked = fixed):

 * https://www.americanas.com.br/ []
 * https://www.beymen.com/ [x]
 * https://www.baymen.com/ [x]
 * https://www.binary.com/ [x]
 * https://www.binomo.com/ [ ]

**Comment by gildas-lormeau** [comment]
@hyperalghorithm any news?

**Comment by hyperalghorithm** [comment]
> Here's a recap of the statuses for each issue (checked = fixed):
> 
> * [ ]  https://www.americanas.com.br/ (net::ERR_CONNECTION_RESET)
> * [x]  https://www.beymen.com/ (overloading of the `URL` constructor by the page, cf. [3e29e43](https://github.com/gildas-lormeau/SingleFile/commit/3e29e43a01e1777af791409f5dc93eeda17d3146) and [670c5a2](https://github.com/gildas-lormeau/SingleFile/commit/670c5a2a78e225b07cea8b97ca8a81b5934bb478))
> * [x]  https://www.binary.com/ (Execution context was destroyed, cf. [544bb12](https://github.com/gildas-lormeau/SingleFile/commit/544bb12ffbb9ac4cbe0b2a8131c7caff43c1191a), [b8902ee](https://github.com/gildas-lormeau/SingleFile/commit/b8902ee266442dcf57ade2c296f4e4c2b4f6100e), [660ad78](https://github.com/gildas-lormeau/SingleFile/commit/660ad7857e60fb66b3a2f9a2341057599fd0fa46) and [f6efdc9](https://github.com/gildas-lormeau/SingleFile/commit/f6efdc97bb8e803299cd7b3cc04abd58a2d17de8))
> * [ ]  https://www.binomo.com/ (Navigation Timeout Exceeded)
(sorry for the late reply)
baymen was a wrong copy paste on my part, i've wrote it before... the rest is correct.

anyway. I've spent a few days researching into selenium, network redirects and trying out python and curl connection. even 'wget' has trouble with binomo. everything works fine when trying the browser extension, the headless statue of the browser is what's causing the problem.

I'll close the issue for now. If you manage to add new features to the project be sure to try these websites and see if they work. Thanks for your support and have a nice day :)

**Comment by gildas-lormeau** [comment]
Thank you also for the feedback @hyperalghorithm! Have a nice day too :)
